### ISSUE TITLE
where are your spark notebooks?

### ISSUE THREAD

**Issue by CDSLabs** [SJSU272Lab/Fall16-Team17#6]

**Comment by ghost** [comment]
We have used python for analysis. As most of the dataset we had was already structured ( for ex. for the HealthCare.gov dataset which is of 11.65 GB)  we had a database.sqllite file. We also have used kaggle and wrote scripts in python for analysis. 

[For 2015](https://www.kaggle.com/team17/d/hhs/health-insurance-marketplace/2015-average-monthly-premium
)

[For 2014](https://www.kaggle.com/team17/d/hhs/health-insurance-marketplace/2014-average-monthly-premium
)

[For 2016](https://www.kaggle.com/team17/d/hhs/health-insurance-marketplace/2016-average-monthly-premium
)


For comparing the United States health care system with Canada, we have used 

[OCED Dataset](http://stats.oecd.org/index.aspx?DataSetCode=HEALTH_STAT
)

here we can write our own queries in the tool and get result.

Next, we have used:

[Historical Budget Data](http://federal-budget.insidegov.com/l/119/2016-Estimate
)

to get year wise spending and deficit for each year. 

On basis of values, we calculated the increase in federal tax rate and deficit.
[272final (1).xlsx](https://github.com/SJSU272Lab/BetterCare/files/656459/272final.1.xlsx)

In order to find out reasons for increasing premiums, we referred many research papers and stats of kaiser foundation.
